// Team mode extension for 2D BattleField Royale
(function(){
'use strict';
const TEAM_COLORS=['#4aa3ff','#ff5555','#55dd77','#bb77ff'];
const state={enabled:false,count:2,assignments:{},names:{},joined:false};
function me(){return window.myPlayer;} function isH(){return !!window.isHost;} function conns(){return window.connections||{};}
function allTeamPlayers(){const a=[];if(me())a.push(me());Object.values(window.remotePlayers||{}).forEach(p=>a.push(p));return a;}
function teamOf(id){return state.assignments[id]||1;} function setTeam(id,t){state.assignments[id]=Math.max(1,Math.min(state.count,t|0));}
function ensureTeams(){allTeamPlayers().forEach((p,i)=>{if(!state.assignments[p.id])setTeam(p.id,(i%state.count)+1);state.names[p.id]=p.name||'플레이어';});}
function payload(){return{type:'TEAM_SETTINGS',enabled:state.enabled,count:state.count,assignments:state.assignments,names:state.names};}
function sendAll(){ensureTeams();const d=payload();if(isH())Object.values(conns()).forEach(c=>{if(c&&c.open)c.send(d)});else if(window.hostConn&&hostConn.open)hostConn.send(d);updateTeamUI();}
function injectCSS(){const s=document.createElement('style');s.textContent=`#teamSettings{width:100%;border:1px solid #4aa3ff;background:rgba(10,20,35,.75);padding:12px;border-radius:8px;margin-top:10px}#teamSettings h3{margin:0 0 8px;color:#4aa3ff}.team-row{display:flex;gap:7px;align-items:center;margin:5px 0}.team-row select{width:105px;padding:6px}.team-dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px}#teamScoreHUD{position:absolute;top:145px;left:20px;z-index:21;display:none;background:rgba(0,0,0,.65);padding:8px 12px;border-radius:7px;font-weight:bold;pointer-events:none}`;document.head.appendChild(s)}
function injectUI(){const host=document.getElementById('hostSettingsControls');if(!host||document.getElementById('teamSettings'))return;const d=document.createElement('div');d.id='teamSettings';d.innerHTML=`<h3>⚔️ 팀전 설정</h3><div class="form-group"><label>팀전 사용</label><select id="teamEnable"><option value="false">개인전</option><option value="true">팀전</option></select></div><div class="form-group"><label>팀 수</label><select id="teamCount"><option>2</option><option>3</option><option>4</option></select></div><div class="form-group"><label>팀 배정</label><select id="teamAssignMode"><option value="manual">방장이 직접 설정</option><option value="auto">자동 균등 배정</option></select></div><div id="teamPlayerList"></div><button id="teamApply" style="margin-top:8px;background:#4aa3ff">팀 설정 적용</button>`;host.appendChild(d);['teamEnable','teamCount','teamAssignMode'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{readUI();updateTeamUI();}));document.getElementById('teamApply').onclick=()=>{readUI();ensureTeams();sendAll();};}
function readUI(){state.enabled=document.getElementById('teamEnable')?.value==='true';state.count=parseInt(document.getElementById('teamCount')?.value||2);if(document.getElementById('teamAssignMode')?.value==='auto')allTeamPlayers().forEach((p,i)=>setTeam(p.id,(i%state.count)+1));}
function updateTeamUI(){const list=document.getElementById('teamPlayerList');if(!list)return;ensureTeams();if(!state.enabled){list.innerHTML='<div style="color:#aaa;margin-top:7px">팀전을 사용하지 않습니다.</div>';return;}list.innerHTML=allTeamPlayers().map(p=>{const opts=Array.from({length:state.count},(_,i)=>`<option value="${i+1}" ${teamOf(p.id)===i+1?'selected':''}>팀 ${i+1}</option>`).join('');return `<div class="team-row"><span style="flex:1">${esc(p.name||p.id)}</span><select data-team-id="${p.id}">${opts}</select></div>`}).join('');list.querySelectorAll('select[data-team-id]').forEach(x=>x.onchange=()=>{setTeam(x.dataset.teamId,parseInt(x.value));sendAll();});}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function injectHUD(){if(document.getElementById('teamScoreHUD'))return;const d=document.createElement('div');d.id='teamScoreHUD';document.getElementById('gameFrame').appendChild(d);}
function updateHUDTeam(){const d=document.getElementById('teamScoreHUD');if(!d||!state.enabled)return;const ps=allTeamPlayers(),scores=Array.from({length:state.count},()=>0);ps.forEach(p=>scores[teamOf(p.id)-1]+=p.kills||0);d.innerHTML=scores.map((v,i)=>`<span style="color:${TEAM_COLORS[i]}">팀 ${i+1} ${v}</span>`).join('　');d.style.display='block';}
function playStep(data){try{const p=me();if(!p)return;const d=Math.hypot(data.x-p.x,data.y-p.y);if(d>900)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;window.__stepAC=window.__stepAC||new AC();const a=window.__stepAC,o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.value=95;g.gain.setValueAtTime(Math.max(.001,.045*(1-d/900)),a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.08);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.08);}catch(e){}}
function wrapNetwork(){const old=window.handleNetworkData;if(!old||old.__teamWrapped)return;window.handleNetworkData=function(data){if(data.type==='TEAM_SETTINGS'){state.enabled=!!data.enabled;state.count=data.count||2;state.assignments=Object.assign({},data.assignments||{});state.names=Object.assign({},data.names||{});updateTeamUI();updateHUDTeam();return;}if(data.type==='TEAM_KILL_EVENT'){if(data.killerId===me().id){me().kills++;if(typeof window.showKillNotification==='function')window.showKillNotification();}updateHUDTeam();return;}if(data.type==='FOOTSTEP_EVENT'){if(data.playerId!==me().id){window.__teamFootsteps=window.__teamFootsteps||[];window.__teamFootsteps.push(data);playStep(data);}return;}old(data);updateHUDTeam();};window.handleNetworkData.__teamWrapped=true;}
function patchJoin(){const oldJ=window.joinRoom;if(oldJ&&!oldJ.__teamWrapped){window.joinRoom=function(){oldJ();setTimeout(()=>{if(window.hostConn&&!state.joined){state.joined=true;hostConn.send({type:'TEAM_JOIN',player:{id:me().id,name:me().name}})}},1000)};window.joinRoom.__teamWrapped=true;}const oldC=window.createRoom;if(oldC&&!oldC.__teamWrapped){window.createRoom=function(){oldC();setTimeout(()=>{ensureTeams();updateTeamUI();},500)};window.createRoom.__teamWrapped=true;}}
function patchConnections(){if(!isH())return;Object.values(conns()).forEach(c=>{if(c.open&&!c.__teamAnnounced){c.__teamAnnounced=true;c.send(payload());}});}
function patchCombat(){const old=window.addKill;if(old&&!old.__teamWrapped){window.addKill=function(killerId){old(killerId);if(state.enabled&&isH())Object.values(conns()).forEach(c=>{if(c.open)c.send({type:'TEAM_KILL_EVENT',killerId:killerId});});updateHUDTeam();};window.addKill.__teamWrapped=true;}}
function patchFootsteps(){const old=window.update;if(!old||old.__teamFootWrapped)return;let lastStep=0;window.update=function(){old();const p=me();if(!p||!window.gameStarted||p.isDead||p.hp<=0)return;const now=Date.now();if(p.isMoving&&now-lastStep>330){lastStep=now;const ev={type:'FOOTSTEP_EVENT',playerId:p.id,x:p.x,y:p.y,team:teamOf(p.id)};if(isH())Object.values(conns()).forEach(c=>{if(c.open)c.send(ev)});else if(window.hostConn&&hostConn.open)hostConn.send(ev);}};window.update.__teamFootWrapped=true;}
function patchRender(){const old=window.render;if(old&&!old.__teamWrapped){window.render=function(){old();if(!state.enabled)return;const c=document.getElementById('gameCanvas'),x=c.getContext('2d');Object.values(window.remotePlayers||{}).forEach(p=>{if(p.isDead||p.hp<=0)return;const t=teamOf(p.id);x.save();x.translate(c.width/2-window.camera.x+p.x,c.height/2-window.camera.y+p.y);x.strokeStyle=TEAM_COLORS[(t-1)%TEAM_COLORS.length];x.lineWidth=3;x.beginPath();x.arc(0,0,27,0,Math.PI*2);x.stroke();x.restore();});};window.render.__teamWrapped=true;}}
function patchVictory(){const old=window.updateHUD;if(!old||old.__teamVictoryWrapped)return;window.updateHUD=function(){old();updateHUDTeam();if(state.enabled&&window.gameStarted&&!window.gameEnded){const alive=allTeamPlayers().filter(p=>p.hp>0&&!p.isDead);if(alive.length>1&&alive.length>0){const t=teamOf(alive[0].id);if(alive.every(p=>teamOf(p.id)===t)&&typeof window.triggerEndGame==='function')window.triggerEndGame();}}};window.updateHUD.__teamVictoryWrapped=true;}
function boot(){injectCSS();injectUI();injectHUD();wrapNetwork();patchJoin();patchConnections();patchCombat();patchFootsteps();patchRender();patchVictory();updateTeamUI();updateHUDTeam();}
setTimeout(boot,0);setInterval(boot,500);setInterval(patchConnections,1000);
})();
